In [1]:
import numpy as np
from fetch_data import qm9_fetch, qm9_fetch_local
# import dmol

In [2]:
data = qm9_fetch_local(num_records = 50)

Found existing cache file, delete if you want to re-fetch

In [ ]:
from helpers import print_record
print_record(data[0])

Number of atoms:  5
Atomic numbers of atoms:  [6 1 1 1 1]

          x         y         z  Partial Charge
0 -0.012698  1.085804  0.008001       -0.535689
1  0.002150 -0.006031  0.001976        0.133921
2  1.011731  1.463751  0.000277        0.133922
3 -0.540815  1.447527 -0.876644        0.133923
4 -0.523814  1.437933  0.906397        0.133923

                                                             0
Consecutive, 1-based integer identifier of mole...    1.000000
Rotational constant A                               157.711807
Rotational constant B                               157.709976
Rotational constant C                               157.706985
Dipole moment                                         0.000000
Isotropic polarizability                             13.210000
Energy of Highest occupied molecular orbital (H...   -0.387700
Energy of Lowest unoccupied molecular orbital (...    0.117100
Gap, difference between LUMO and HOMO                 0.504800
Electronic spatial extent                            35.364101
Zero point vibrational energy                         0.044749
Internal energy at 0 K                              -40.478931
Internal energy at 298.15 K                         -40.476063
Enthalpy at 298.15 K                                -40.475117
Free energy at 298.15 K                             -40.498596
Heat capacity at 298.15 K                             6.469000

In [ ]:
import jax.numpy as jnp
import jax.example_libraries.optimizers as optimizers
import jax
import warnings
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")


@jax.jit
def baseline_model(nodes, w, b):
    # get sum of each element type
    atom_count = jnp.sum(nodes, axis=0)
    yhat = atom_count @ w + b
    return yhat


def baseline_loss(nodes, y, w, b):
    return (baseline_model(nodes, w, b) - y) ** 2


baseline_loss_grad = jax.grad(baseline_loss, (2, 3))
w = np.ones(16)
b = 0.0

ModuleNotFoundError: No module named 'jax'

## Baseline model

In [5]:
import torch
import warnings
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")


def baseline_model(nodes, w, b):
    """
    nodes: (n_atoms, n_elements)
    w:     (n_elements,)
    b:     scalar
    """
    # get sum of each element type
    atom_count = torch.sum(nodes, dim=0)
    yhat = atom_count @ w + b
    return yhat


def baseline_loss(nodes, y, w, b):
    return (baseline_model(nodes, w, b) - y) ** 2


# Parameters
w = torch.ones(16, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# Example
nodes = torch.randn(5, 16)
y = torch.tensor(3.5)

loss = baseline_loss(nodes, y, w, b)

# Compute gradients
loss.backward()

print("Loss:", loss.item())
print("dw:", w.grad)
print("db:", b.grad)

ModuleNotFoundError: No module named 'torch'